############   Install and load the package mvoutlier ############   
install.packages("mvoutlier")
library(mvoutlier)
#Load the data
data(humus)
str(humus)

#Close attention to the variables. Note that the first variable corresponds to an identification number rather 
#than a data point and should not be included in outlier detection analysis. Additionally, the variables XCOO 
#and YCOO correspond to map coordinates from which the soil samples were taken. 

xy <- humus[,c("XCOO","YCOO")] # X and Y Coordinates
x <- log(humus[, c("As", "Cd", "Co", "Cu", "Mg", "Pb", "Zn")])

############   Mahalanobis distance ############   
#Plot of classic Mahalanobis distance with classical quantile against robust MD 
#based on MCD with the adjusted quantile
distances <- dd.plot(x, quan=1/2, alpha=0.025)
str(distances$md.cla)
str(distances$md.rob)

############   2 dimensional plot   ############   
#The color.plot function of this package provides outlier classification visualization 
#for a given dataset where input arguments are as follows:
#x: a 2-dimensional data frame or matrix
#quan: amount of observations to be used for MCD calculation
#alpha: amount of observations used to calculate the adjusted quantile

colorData <- color.plot(x[,c(1,2)], quan=1/2, alpha=0.025)

#The plot generated by this function represents the euclidean distance as a color, where blue represent 
#small distances, and red represent large distances from the data set minimum. Mahalanobis distances are 
#represented by a symbol. The function also draws four ellipsoids where the Mahalanobis Distances are constant. 
#The constant values correspond to the 25%, 50%, and 75% and adjusted quantiles. Finally, this function can 
#provide us with vectors containing Mahalanobis Distance, Euclidean Distances, and a logical vector of outliers.

############   Map plot   ############   
#Interpretation Plots
#The mvoutlier package provides several useful tools for analyzing and understanding our multivariate outliers. 
#Many of these tools are very specific to the test datasets and are based off of the geo-locations the data was 
#collected from, however, they still provide a strong example of how this type of data can be utilized. 
#For example, we can plot a map with outliers identified.

# kola background is a map from which humus samples were taken
m=map.plot(xy, x, symb=TRUE)

#Univariate visualization
uni.plot(x,symb=TRUE)

#Outliers
indexes=1:617
out=indexes[m$outliers]
out






